/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as RitRouteImport } from './routes/rit'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const RitRoute = RitRouteImport.update({
  id: '/rit',
  path: '/rit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/rit': typeof RitRoute
  '/submit': typeof SubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/rit': typeof RitRoute
  '/submit': typeof SubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/rit': typeof RitRoute
  '/submit': typeof SubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/community' | '/login' | '/missions' | '/profile' | '/rit' | '/submit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/community' | '/login' | '/missions' | '/profile' | '/rit' | '/submit'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/login'
    | '/missions'
    | '/profile'
    | '/rit'
    | '/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRoute
  ProfileRoute: typeof ProfileRoute
  RitRoute: typeof RitRoute
  SubmitRoute: typeof SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rit': {
      id: '/rit'
      path: '/rit'
      fullPath: '/rit'
      preLoaderRoute: typeof RitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRoute,
  ProfileRoute: ProfileRoute,
  RitRoute: RitRoute,
  SubmitRoute: SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
